### ISSUE TITLE
Need to add IBTS roundfish areas

### ISSUE THREAD

**Issue by martinpastoors** [fishvice/tidydatras#2]
North Sea IBTS roundfish areas are needed to be included for index calculation. Can those areas be linked directly to the ICES spatial facility?

**Comment by einarhjorleifsson** [comment]
the background to the NS IBTS roundfish areas is this: https://www.ices.dk/data/Documents/DATRAS/Indices_Calculation_Steps_IBTS.pdf

**Comment by einarhjorleifsson** [comment]
if the roundfish areas are in line with the statistical rectangle (i.e. the boundaries do not cross) i think this is a simple lookup-table (rather than a spatial object) that has statrect and ibts_rf as variables. the third variable could possibly be the weight as listed in the link provided above. will look into generating that.

**Comment by einarhjorleifsson** [comment]
seems like it is the case that the boundaries of the ibts is along the ices statistical rectangles:


```
library(sf)
library(mapview)
library(tidyverse)
rf <- 
  gisland::read_sf_ftp("NS_IBTS_RF") |> 
  st_make_valid() |> 
  mutate(rf_name = as.integer(AreaName),
         area = st_area(geom)) |> 
  select(rf_name,
         area)
st_is_valid(rf)

g <- 
  expand_grid(lon = seq(-6, 14, by = 0.5) + 0.1,
              lat = seq(48, 63, by = 0.5) + 0.1) |> 
  st_as_sf(coords = c("lon", "lat"),
           crs = 4326,
           remove = FALSE) |> 
  st_join(rf |> select(rf_name))
mapview(rf, zcol = "rf_name") + 
  mapview(g, zcol = "rf_name")
```
now one need only to get the area of each rectangle as dictated in annex 3 in the link above.

**Comment by einarhjorleifsson** [comment]
ooh, and the ices rectangle vs ibts rf area is just obtained via this:

`g |> 
  st_drop_geometry() |> 
  drop_na() |> 
  mutate(ir = geo::d2ir(lat, lon)) |> 
  select(ir, rf_name) |> 
  distinct()`

**Comment by einarhjorleifsson** [comment]
a note of caution: tidydatras should focus on the generics, not being too specific to a particular survey. including the ibts-roundfish area (shapeflie or rectangle-rf area lookup table) may be too specific. this and other shape things possibly belong to another package that provides  R-convenient functions to read objects from a geoserver, e.g. the ices webserver (gisland is a canditate).

**Comment by martinpastoors** [comment]
Added ibts_rect.rda to data. Taken from https://www.ices.dk/data/Documents/DATRAS/Indices_Calculation_Steps_IBTS.pdf (annex 3). If we would add the RF areas to that file again, we could use it directly for index calculation

**Comment by martinpastoors** [comment]
Probably better to ignore roundfish areas.

**Comment by martinpastoors** [comment]
Closed
